apiVersion: v1
kind: Namespace
metadata:
  name: conduit-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: conduit-dev
  name: conduit-ui-deployment
  labels:
    app: conduit-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: conduit-ui
  template:
    metadata:
      labels:
        app: conduit-ui
    spec:
      containers:
      - name: conduit-ui
        image: chikamalu/conduit-ui:latest
        ports:
        - containerPort: 4100
---
apiVersion: v1
kind: Service
metadata:
  namespace: conduit-dev
  name: conduit-ui-service
spec:
  type: LoadBalancer
  selector:
    app: conduit-ui
  ports:
    - protocol: TCP
      port: 4100
      targetPort: 4100